### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by NoroHime** [ldcivan/ddcheck_plugin#1]
```
[YzBot][13:50:34.754][ERRO] [DDchecker][cha_chengfen]
[YzBot][13:50:34.754][ERRO] TypeError: JSON.stringify(...).replaceAll is not a f
unction
    at example.cha_chengfen (file:///D:/Yunzai-Bot/plugins/example/%E6%9F%A5%E6%
88%90%E5%88%86.js:132:87)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PluginsLoader.deal (file:///D:/Yunzai-Bot/lib/plugins/loader.js:251
:52)
```
顺带一提搜图插件下也同样存在该问题
```
[YzBot][13:52:52.459][ERRO] [pic_search][pic_search]
[YzBot][13:52:52.459][ERRO] TypeError: JSON.stringify(...).replaceAll is not a f
unction
    at example.pic_search (file:///D:/Yunzai-Bot/plugins/example/Yunzai_imgSearc
her.js:106:94)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PluginsLoader.deal (file:///D:/Yunzai-Bot/lib/plugins/loader.js:251
:52)
```

**Comment by YujioNako** [comment]
估计是返回了空内容
我对代码做了一点点调整，如果还是有问题，请检查请检查您的网络，看一下是否ping的通saucenao.com和bilibili.com

**Comment by NoroHime** [comment]
> 估计是返回了空内容 我对代码做了一点点调整，如果还是有问题，请检查请检查您的网络，看一下是否ping的通saucenao.com和bilibili.com

破案了，nodejs在v8 8.5才加入String.prorotype.replaceAll，而我的node安装包刚好是2021的
https://stackoverflow.com/questions/66937529/why-doesnt-nodejs-support-string-prototype-replaceall

**Comment by YujioNako** [comment]
草，这我倒是没想到hhhhh
